package ehb;


public enum ActionTypes
{
    NO_OP,
    SET_COLOR_ORANGE,
    SET_COLOR_BLUE,
    SET_COLOR_RED,
    PLAY_ENGAGED_SOUND,
    PLAY_DISENGAGED_SOUND,
    APPLY_TEN_PERCENT_FORCE_INCREASE,
    DISENGAGE_EHB,
    FULLY_ENGAGE_EHB;
}
