package ehb;


public enum StateTypes
{
    PARKED_ENGAGED,
    PARKED_DISENGAGED,
    STOPPED_DISENGAGED,
    MOVING_ENGAGING,
    MOVING_DISENGAGED,
    MOVING_ENGAGED,
    MOVING_DISENGAGING,
    STOPPED_ENGAGED;
}
